{% set name = "pychop" %}
{% set version = "0.4.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pychop/pychop-{{ version }}.tar.gz
  sha256: f4d39405b643286ad8a564b490271fc513a7f9137b0f8b1d5219345de5bf5aba

build:
  number: 0
  script:
    - {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - numpy >=1.17.2
  run:
    - python >={{ python_min }}
    - numpy >=1.17.2
    - pandas
    - dask
    - pytorch >=1.12
    - jax >=0.4.8

test:
  requires:
    - python {{ python_min }}
    - scipy
    - pytest
    - pip
  imports:
    - pychop
    - pychop.np
    - pychop.tch
    - pychop.jx
  commands:
    - pip check

about:
  home: https://github.com/inexascale/pychop
  license: MIT
  license_file: LICENSE
  summary: Python library for simulating low precision floating-point arithmetic
  description: |
    Pychop is a Python library designed to facilitate numerical experimentation with low-precision arithmetic. 
    It supports customizable floating-point formats and a comprehensive set of rounding modes, 
    integrating seamlessly with NumPy, PyTorch, and JAX for efficient low-precision emulation 
    in deep learning and scientific computations.
  doc_url: https://pychop.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/inexascale/pychop
  license_family: MIT

extra:
  recipe-maintainers:
    - eccarson
    - chenxinye
